[package]
name = "manada"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display", "from"] }
dirs = "6.0.0"
itertools = "0.14.0"
petgraph = "0.8.1"
