[aliases]
b = ["byte"]
eb = ["exa", "exabyte"]
gb = ["giga", "gigabyte"]
kb = ["kilo", "kilobyte"]
mb = ["mega", "megabyte"]
pb = ["peta", "petabyte"]
tb = ["terra", "terrabyte"]
yb = ["yotta", "yottabyte"]
zb = ["zotta", "zottabyte"]
